name: betz_cars
description: Betz cars fleet.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3"

dependencies:
  realm: ^1.4.0
  http: ^1.1.0
  mongo_dart: ^0.10.0
  path_provider: ^2.0.10
  url_launcher: ^6.1.12
  intl: ^0.19.0
  card_swiper: ^3.0.1
  font_awesome_flutter: ^10.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - img/golf7.png
    - img/t-roc.png
    - img/polo.png
    - assets/betz-group-logo.png
    - assets/betz-group-black.png
    - assets/betz-group-color.png
    - assets/betz-group-no-background.png
    - assets/betz-group-white.png

flutter_launcher_icons:
  image_path: "assets/betz-group-no-background.png"
  android: true
  ios: false
